### ISSUE TITLE
Possible typo in derivitive function

### ISSUE THREAD

**Issue by JohnLCaron** [spertus/comparison-RLA-betting#1]
Hi Jake:

Ive been studying your COBRA paper, and I noticed that in 

https://github.com/spertus/comparison-RLA-betting/blob/main/comparison_audit_simulations.R, line 19:

```
  derivative <- function(lambda){
    (a - 1/2) * (1 - p_1 - p_2) / (1 + lambda * (a - 1/2)) + (a - 1) * p_1 / (2 - lambda * (1 - a)) + p_2 / (2 - lambda)
  }
```

i think should be (change sign on last term):

```
 derivative <- function(lambda){
    (a - 1/2) * (1 - p_1 - p_2) / (1 + lambda * (a - 1/2)) + (a - 1) * p_1 / (2 - lambda * (1 - a)) - p_2 / (2 - lambda)
  }
```

I see that its not actually used, since optimize apparently operates directly on the function, rather than its derivitive. But seems like its still worth pointing out. 

Im working with Vanessa Teague and colleagues to write an RLA library heavily using Philip's and your (et al) work. 
Im generalizing the function to optimize to use over/understatement rates for all 5 possible assorter values:

```
    fun expected_value_logT(lam: Double): Double {
        return ln(1.0 + lam * (a - mui)) * p0 +
                ln(1.0 + lam * (a*0.5 - mui)) * p1 +
                ln(1.0 - lam * mui) * p2 +
                ln(1.0 + lam * (a*1.5 - mui)) * p3 +
                ln(1.0 + lam * (a*2.0 - mui)) * p4
    }
```
where mui is the population mean under the null for sampling without replacement (=1/2 for sampling with replacement)
(code is kotlin, not R or python).

Anyway, thanks for all your hard work!

Regards, 
John

**Comment by spertus** [comment]
Hi John,

Thanks so much for spotting this. I agree the sign should be negative in the last term. I fixed it here and am also pushing an update to the version on Arxiv. I very much appreciate the tip! 

You are correct that it doesn't matter: optimize just looks along the interval directly and doesn't need derivative information. This should be true for your application as well, since the optimal bet is still a scalar. It might get trickier in higher dimensions, e.g. for stratified audits.   

Your code looks good to me! I'm glad you're continuing with this work; Philip and I are now working on stratified comparison audits at the moment, primarily by implementing the code [here](https://github.com/spertus/UI-NNSMs) on an example audit. Perhaps there's an opportunity to integrate with your new codebase as well? In any event, always happy to chat more as things come up. 

Best,
Jake

**Comment by JohnLCaron** [comment]
Hi Jake:

Your stratified comparison audit work looks very interesting, and I'm
putting it on my list to study. Does it supersede the OneAudit paper or are
those two separate problems?

John

**Comment by spertus** [comment]
Hi John,

Glad you think so :) 

I should mention there is more on stratified comparison audits in particular [here](https://arxiv.org/abs/2207.03379), just in case you haven't come across that article yet. The more recent one is a generalization, which should improve efficiency. 

In my view, stratification does not supersede OneAudit _nor_ are they separate problems... 

There are RLAs where stratification is inherently necessary, e.g. if a law says you have to audit independently across sub-jurisdictions (say, counties in a statewide contest). You cannot use OneAudit in that case. On the other hand, either OneAudit or stratification could be used to run a hybrid audit, one that uses both ballot-level comparison and ballot-polling (or batch-level comparison). It is not yet known which is more efficient for a hybrid audit. Some initial thoughts: The disadvantage of OneAudit is that the ballots are "mixed together" so that you cannot sharply tailor bets to the population; in a stratified audit you could use the comparison-optimal bets in the comparison stratum and the bernoulli-optimal bets in the ballot-polling stratum. The advantage of OneAudit is that there is no stratification penalty, which was a problem for SUITE but not as much for the newer methods we've explored...

It's an interesting problem, one that I hope to explore more soon.

Best,
Jake
